feat: signed configuration

diff --git a/iac/api/trigger b/iac/api/trigger
--- a/iac/api/trigger
+++ b/iac/api/trigger
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+SOCKET_PATH="/var/run/cuos.sock"
+
 cuos_api() {
   local command="$1"
   local json_data="${2:-""}"
@@ -37,6 +39,8 @@ INPUT="{}"
 if [[ -z "${COMMAND}" ]]; then
   read -r INPUT
   COMMAND="$(jq -r '.app_command // empty' <<< "${INPUT}")"
+elif [[ "${2:-}" == "-" ]]; then
+  read -r INPUT
 fi
 
 if [[ "${COMMAND}" = "" || "${COMMAND}" = "help" || "${COMMAND}" = "--help" ]]; then
@@ -64,7 +68,9 @@ elif [[ "${COMMAND}" = "state" ]]; then
 	cat /volume/state.json
 
 elif [[ "${COMMAND}" = "config" ]]; then
-  SIGNING_KEYS_FILE="/volume/signing_keys"
+  set -x
+
+  SIGNING_KEYS_FILE="${T_SIGNING_KEYS_FILE:-"/volume/signing_keys"}"
   compact="$(echo "${INPUT}" | jq -r '.config // empty')"
   ns="file"
 
@@ -85,18 +91,23 @@ elif [[ "${COMMAND}" = "config" ]]; then
   [ -n "$payload_b64url" ] && [ -n "$sig_b64url" ] || { echo "invalid compact input"; exit 2; }
 
   # decode payload to json (kept in variable)
-  json="$(echo "$payload_b64url" | b64url_to_b64 | base64 -d)" || { echo "invalid payload"; exit 3; }
+  json="$(printf '%s' "$payload_b64url" | b64url_to_b64 | base64 -d)" || { echo "invalid payload"; exit 3; }
 
-  principal="$(ssh-keygen -Y find-principals -f "${SIGNING_KEYS_FILE}" \
-    -s <(echo "$sig_b64url" | b64url_to_b64 | base64 -d))" || exit 4
+  if ! principal="$(ssh-keygen -Y find-principals -f "${SIGNING_KEYS_FILE}" \
+      -s <(printf '%s' "$sig_b64url" | b64url_to_b64 | base64 -d))"; then
+    echo "no principal identified."
+    exit 4
+  fi
 
 
-  echo "$json" | ssh-keygen -Y verify \
-    -f "${SIGNING_KEYS_FILE}" \
-    -n "$ns" \
-    -I "$principal" \
-    -s <(printf '%s' "$sig_b64url" | b64url_to_b64 | base64 -d) \
-    || exit 5
+  if ! printf '%s' "$json" | ssh-keygen -Y verify \
+      -f "${SIGNING_KEYS_FILE}" \
+      -n "$ns" \
+      -I "$principal" \
+      -s <(printf '%s' "$sig_b64url" | b64url_to_b64 | base64 -d); then
+    echo "Can not validate."
+    exit 5
+  fi
 
   now="$(date +%s)"
   iat="$(printf '%s' "$json" | jq -r '.iat // empty')"
@@ -121,6 +132,6 @@ elif [[ "${COMMAND}" = "config" ]]; then
   exit 7
 
 else
-	echo "No valid command provided. Exiting."
+  echo "No valid command provided. Exiting."
 
 fi
