feat: cuos-webui without CuOS

diff --git a/iac/api/trigger b/iac/api/trigger
--- a/iac/api/trigger
+++ b/iac/api/trigger
@@ -82,10 +82,10 @@ elif [[ "${COMMAND}" = "config" ]]; then
   payload_b64url="${compact%%.*}"
   sig_b64url="${compact#*.}"
 
-  [ -n "$payload_b64url" ] && [ -n "$sig_b64url" ] || { echo "invalid compact input" >&2; exit 2; }
+  [ -n "$payload_b64url" ] && [ -n "$sig_b64url" ] || { echo "invalid compact input"; exit 2; }
 
   # decode payload to json (kept in variable)
-  json="$(echo "$payload_b64url" | b64url_to_b64 | base64 -d)" || { echo "invalid payload" >&2; exit 3; }
+  json="$(echo "$payload_b64url" | b64url_to_b64 | base64 -d)" || { echo "invalid payload"; exit 3; }
 
   principal="$(ssh-keygen -Y find-principals -f "${SIGNING_KEYS_FILE}" \
     -s <(echo "$sig_b64url" | b64url_to_b64 | base64 -d))" || exit 4
@@ -95,21 +95,22 @@ elif [[ "${COMMAND}" = "config" ]]; then
     -f "${SIGNING_KEYS_FILE}" \
     -n "$ns" \
     -I "$principal" \
-    -s <(printf '%s' "$sig_b64url" | b64url_to_b64 | base64 -d) >&2 \
+    -s <(printf '%s' "$sig_b64url" | b64url_to_b64 | base64 -d) \
     || exit 5
 
   now="$(date +%s)"
   iat="$(printf '%s' "$json" | jq -r '.iat // empty')"
   iat="${iat%%.*}"
   if ! [[ "${iat}" =~ ^[0-9]+$ ]]; then
-    echo "invalid or missing iat: $iat" >&2
+    echo "invalid or missing iat: $iat"
     exit 6
   fi
 
   # Signature is only valid for 15mins:
   if (( now > iat - 60 )) && (( now < iat + 900 )); then
     name=$(echo "${json}" | jq -r '.name // "unknown"')
-    echo "Signed by ${name}" >&2
+    echo "Config signed by ${name}"
+    echo "Passing config to system ..."
 
     echo "${json}" | jq '{"config": .config}' | cuos_api "update" "-"
     exit 0
